stages:
 - deploy

deploy:
 image: node:16
 tags:
   - aws
   - barbarians
 stage: deploy
 rules:
   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
     when: always
   - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
     when: manual
 script:
   - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
   - npm install
   - npm run build
   - npm run test:unit
   - npm publish